<h2>Welcome</h2>
<img src="./images/big.png">
<h3>Why should you drink coffee?</h3>
<p>Coffee does more than boost your energy. A few daily cups of coffee may also lower your risk of type 2 diabetes and depression, support weight management, and help you live a longer life. Coffee is a beloved beverage known for its ability to fine-tune your focus and boost your energy levels. In fact, many people depend on their daily cup of joe right when they wake up to get their day started on the right foot. In addition to its energizing effects, coffee has been linked to a long list of potential health benefits, giving you all the more reason to get brewing.</p>
<h3>Boosts energy levels</h3>
<p>Coffee contains caffeine, a central nervous system stimulant that is known for its ability to fight fatigue and increase energy levels. This is because caffeine blocks the receptors of a neurotransmitter called adenosine, and this increases levels of other neurotransmitters in your brain that regulate your energy levels, including dopamine. One small study found that consuming caffeine increased time to exhaustion during a cycling exercise by 12% and significantly reduced subjective levels of fatigue in participants.</p>
<h3>May be linked to a lower risk of type 2 diabetes</h3>
<p>Some research suggests that consuming coffee regularly could be associated with a decreased risk of developing type 2 diabetes over the long term. In fact, one review of 30 studies found that each cup of coffee people consumed per day was linked to a 6% lower risk of developing type 2 diabetes. This is thought to be due to coffee’s ability to preserve the function of the beta cells in your pancreas, which are responsible for producing insulin to regulate blood sugar levels.</p>
<h3>Could support brain health</h3>
<p>Although studies have turned up mixed results, some research suggests that coffee may help protect against certain neurodegenerative disorders, including Alzheimer’s disease and Parkinson’s disease. According to one review of 13 studies, people who regularly consumed caffeine had a significantly lower risk of developing Parkinson’s disease. What’s more, caffeine consumption also slowed the progression of Parkinson’s disease over time. Another review of 11 observational studies in more than 29,000 people also found that the more coffee people consumed, the lower their risk of Alzheimer’s disease.</p>
<h3>Linked to a lower risk of depression</h3>
<p>Some studies have found that drinking coffee could be associated with a lower risk of depression. According to one review of seven studies, each cup of coffee people consumed per day was linked to an 8% lower risk of depression. Another study found that drinking at least four cups of coffee each day was associated with a significantly lower risk of depression, compared with drinking just one cup per day. What’s more, one study in more than 200,000 people showed that drinking coffee was linked to a lower risk of death by suicide.</p>